# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
logo: "/assets/images/my_logo.png"
title: Abhinaba Saha
email: abhinaba.saha9590@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  
twitter_username: saharintu
github_username: abhinabasaha
minimal_mistakes_skin: dirt
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: https://en.wikipedia.org/wiki/Kolkata # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Abhinaba Saha"
  avatar : "/assets/images/informal.jpg"
  bio    : "A researcher and keen explorer having M.Tech in Intelligent Automation and Robotics, [JU](http://www.jaduniv.edu.in/). My research interests includes Artificial Intelligence, Machine Learning, Deep Learning, Data Science, Computer vision, Pattern Recognition, Robotics, Python, Linux, Cloud Computing."
            
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/abhinabasaha/"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://abhinabasaha.in"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/saharintu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github" #"fab fa-github"  #"fab fa-fw fa-github" 
      url: "https://github.com/abhinabasaha"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/abhi_naba/"
    - label: "Youtube"
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/playlist?list=PLoStSiNKte3UHH_JR4Q1yFWzdtsfvzr7y"
    

footer:
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/abhinabasaha/"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://abhinabasaha.in"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/saharintu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github" #"fab fa-fw fa-github"  
      url: "https://github.com/abhinabasaha"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/abhi_naba/"
    - label: "Youtube"
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/playlist?list=PLoStSiNKte3UHH_JR4Q1yFWzdtsfvzr7y"
      
      
      
comments:
  provider: "disqus"
  disqus:
    shortname: "abhinabasaha"

      
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
  analytics:
    provider: "google-gtag" #"google-universal" 
    google:
      tracking_id: "UA-179540128-1" 
      anonymize_ip: false # default

